name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::209479295186:oidc-provider/token.actions.githubusercontent.com"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "puchalvert-us-east-2-terraform-statefile"
      aws-lock-dynamodb-table: "puchalvert_us_east_2_terraform_lock"