name: "PROD DEPLOY"

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      aws-assume-role-arn: "arn:aws:iam::209479295186:oidc-provider/token.actions.githubusercontent.com"
      aws-region: "us-east-2"
