name: Terraform AWS EC2 Deployment

on:
  workflow_call:
    inputs:
      aws-assume-role-arn:
        description: 'ARN del rol de IAM para asumir'
        type: string
        required: true
      aws-region:
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Configura un entorno en GitHub (opcional)

    steps:
      # Paso 1: Descargar el código
      - name: Checkout
        uses: actions/checkout@v4

      # Paso 2: Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6.6"  # Usa tu versión

      # Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ inputs.aws-assume-role-arn }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ inputs.aws-region }}
        
      # Paso 3: Inicializar Terraform
      - name: Terraform Init
        run: terraform init
        
      # Paso 4: Validar sintaxis
      - name: Terraform Validate
        run: terraform validate

      # Paso 5: Planificar cambios
      - name: Terraform Plan
        run: terraform plan -input=false
        
      # Paso 6: Aplicar cambios (solo en rama master)
      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        run: terraform apply -auto-approve -input=false
        